# Host: OrbStack NixOS dev container on the MacBook.
# OrbStack-specific plumbing lives in incus.nix / orbstack.nix (copied from
# the machine's generated /etc/nixos — refresh them if OrbStack regenerates).
# Product code lives in ../../modules and is shared with future hardware hosts.

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix

      # ─── Appliance layer ───────────────────────────
      ../../modules/base.nix
      ../../modules/inference.nix
      ../../modules/webui.nix
      ../../modules/odysseus.nix
    ];

  users.users.jackbergin = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" "audio" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/jackbergin";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "America/New_York";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
      MIICDTCCAbKgAwIBAgIQFyjNr0b0vRLZ39Fp23+peDAKBggqhkjOPQQDAjBmMR0w
      GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
      cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
      IENBMB4XDTI2MDExNDAwMDAzNVoXDTM2MDExNDAwMDAzNVowZjEdMBsGA1UEChMU
      T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
      aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
      ByqGSM49AgEGCCqGSM49AwEHA0IABM5D3M/ejMte6nsWZE2cWqot/ENDOiHVkbZe
      LhFfubFlVeSW0cj5P+RVHAAQ7TtDSpNcxz9CLAMmGdYrXLiu0LyjQjBAMA4GA1Ud
      DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSVR/K3upRQCaE9
      OjfZmArR465XYjAKBggqhkjOPQQDAgNJADBGAiEAqYnQptYY20x5aIqNCi3fSX6q
      P6BMA8aLuIYH7i9+uocCIQCEEGsU871ImENEPOwpwUTQ7gpda24SWYyGddesMSHv
      Ig==
      -----END CERTIFICATE-----
    ''
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # For more information, see `man configuration.nix` or
  # https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.11"; # Did you read the comment?
}
